# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(488, 322)
        Form.setStyleSheet("background-color: rgb(43, 43, 43);\n"
"color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.chat_text = QtWidgets.QTextEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.chat_text.setFont(font)
        self.chat_text.setStyleSheet("selection-background-color: rgb(161, 75, 0);\n"
"\n"
"QScrollBar::handle {\n"
"border-syle: outset;\n"
"background: #444444;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QScrollBar::handle::pressed {\n"
"background: rgb(161, 75, 0);\n"
"}\n"
"\n"
"QScrollBar::add-page {\n"
"background-color: rgb(43, 43, 43);\n"
"}")
        self.chat_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.chat_text.setUndoRedoEnabled(False)
        self.chat_text.setReadOnly(True)
        self.chat_text.setObjectName("chat_text")
        self.horizontalLayout_4.addWidget(self.chat_text)
        self.verticalScrollBar = QtWidgets.QScrollBar(Form)
        self.verticalScrollBar.setStyleSheet("QScrollBar:vertical {\n"
"     border: 0px solid;\n"
"     background: rgb(43, 43, 43);\n"
"     width: 15px;\n"
"     margin: 16px 0 16px 0;\n"
" }\n"
" QScrollBar::handle:vertical {\n"
"     background: rgb(161, 75, 0);\n"
"     border-width: 2px;\n"
"     border-radius: 10px;\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: 0px solid;\n"
"     background-color: rgb(43, 43, 43);\n"
"     height: 16px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
"     image: url(:/arrows/up_arrow_dark.png);\n"
" }\n"
"\n"
" QScrollBar::sub-line:vertical {\n"
"     border: 0px solid;\n"
"     background: rgb(43, 43, 43);\n"
"     height: 16px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
"     image: url(:/arrows/down_arrow_dark.png);\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }")
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.horizontalLayout_4.addWidget(self.verticalScrollBar)
        self.verticalScrollBar_2 = QtWidgets.QScrollBar(Form)
        self.verticalScrollBar_2.setStyleSheet("QScrollBar:vertical {\n"
"     border: 0px solid;\n"
"     background: rgb(43, 43, 43);\n"
"     width: 15px;\n"
"     margin: 16px 0 16px 0;\n"
" }\n"
" QScrollBar::handle:vertical {\n"
"     background: rgb(161, 75, 0);\n"
"     border-width: 2px;\n"
"     border-radius: 10px;\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: 0px solid;\n"
"     background-color: rgb(43, 43, 43);\n"
"     height: 16px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
"     image: url(:/arrows/up_arrow_dark.png);\n"
" }\n"
"\n"
" QScrollBar::sub-line:vertical {\n"
"     border: 0px solid;\n"
"     background: rgb(43, 43, 43);\n"
"     height: 16px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
"     image: url(:/arrows/down_arrow_dark.png);\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }")
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.horizontalLayout_4.addWidget(self.verticalScrollBar_2)
        self.members_list = QtWidgets.QTreeWidget(Form)
        self.members_list.setMinimumSize(QtCore.QSize(144, 0))
        self.members_list.setMaximumSize(QtCore.QSize(144, 16777215))
        self.members_list.setStyleSheet("selection-background-color: rgb(161, 75, 0);")
        self.members_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.members_list.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.members_list.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.SelectedClicked)
        self.members_list.setIndentation(10)
        self.members_list.setRootIsDecorated(False)
        self.members_list.setAnimated(False)
        self.members_list.setWordWrap(True)
        self.members_list.setExpandsOnDoubleClick(True)
        self.members_list.setObjectName("members_list")
        self.members_list.header().setVisible(False)
        self.members_list.header().setStretchLastSection(True)
        self.horizontalLayout_4.addWidget(self.members_list)
        self.list_frame = QtWidgets.QWidget(Form)
        self.list_frame.setMinimumSize(QtCore.QSize(144, 0))
        self.list_frame.setObjectName("list_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.list_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.error_getting_member_list = QtWidgets.QLabel(self.list_frame)
        self.error_getting_member_list.setMinimumSize(QtCore.QSize(144, 200))
        self.error_getting_member_list.setMaximumSize(QtCore.QSize(144, 200))
        self.error_getting_member_list.setTextFormat(QtCore.Qt.RichText)
        self.error_getting_member_list.setAlignment(QtCore.Qt.AlignCenter)
        self.error_getting_member_list.setWordWrap(True)
        self.error_getting_member_list.setObjectName("error_getting_member_list")
        self.verticalLayout_2.addWidget(self.error_getting_member_list)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.close_panel_btn = QtWidgets.QPushButton(self.list_frame)
        self.close_panel_btn.setMaximumSize(QtCore.QSize(60, 24))
        self.close_panel_btn.setObjectName("close_panel_btn")
        self.horizontalLayout.addWidget(self.close_panel_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_4.addWidget(self.list_frame)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 0, 0, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.message_text = QtWidgets.QLineEdit(Form)
        self.message_text.setEnabled(False)
        self.message_text.setMinimumSize(QtCore.QSize(0, 23))
        self.message_text.setStyleSheet("selection-background-color: rgb(161, 75, 0);\n"
"color: rgb(79, 79, 79);")
        self.message_text.setObjectName("message_text")
        self.horizontalLayout_5.addWidget(self.message_text)
        self.send_msg_btn = QtWidgets.QPushButton(Form)
        self.send_msg_btn.setEnabled(False)
        self.send_msg_btn.setStyleSheet("border-color: rgb(255, 119, 0); selection-background-color: rgb(255, 119, 0); color: #4f4f4f")
        self.send_msg_btn.setObjectName("send_msg_btn")
        self.horizontalLayout_5.addWidget(self.send_msg_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addLayout(self.verticalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Чат"))
        self.members_list.headerItem().setText(0, _translate("Form", "Members"))
        self.error_getting_member_list.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Нам пока не удалось получить список участников.</span></p><p>Попробуйте включить отладчик строк в настройках и сообщить <a href=\"https://github.com/tinelix/irc-client/issues\"><span style=\" text-decoration: underline; color:#1d99f3;\">разработчикам</span></a> об этой проблеме.</p><p>Строка в консоли должна быть в таком формате:<br/><span style=\" font-size:7pt;\">&lt;сервер&gt; &lt;код&gt; &lt;ваш_ник&gt; &lt;ник1&gt; &lt;ник2&gt;</span></p></body></html>"))
        self.close_panel_btn.setText(_translate("Form", "Закрыть"))
        self.message_text.setText(_translate("Form", "На данный момент отправить сообщение нельзя"))
        self.send_msg_btn.setText(_translate("Form", "Отправить"))
import resources_rc
