# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aboutprogram.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(408, 331)
        Dialog.setMinimumSize(QtCore.QSize(408, 300))
        Dialog.setMaximumSize(QtCore.QSize(624, 404))
        Dialog.setStyleSheet("background-color: rgb(43, 43, 43);\n"
"color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.icon_label = QtWidgets.QLabel(Dialog)
        self.icon_label.setMinimumSize(QtCore.QSize(0, 80))
        self.icon_label.setMaximumSize(QtCore.QSize(16777215, 140))
        self.icon_label.setStyleSheet("image: url(:/icons/icon_64_64.png);")
        self.icon_label.setText("")
        self.icon_label.setObjectName("icon_label")
        self.verticalLayout_2.addWidget(self.icon_label)
        self.progname = QtWidgets.QLabel(Dialog)
        self.progname.setMinimumSize(QtCore.QSize(0, 28))
        self.progname.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.progname.setFont(font)
        self.progname.setStyleSheet("selection-color: rgb(255, 119, 0);")
        self.progname.setAlignment(QtCore.Qt.AlignCenter)
        self.progname.setWordWrap(True)
        self.progname.setObjectName("progname")
        self.verticalLayout_2.addWidget(self.progname)
        self.description_label = QtWidgets.QLabel(Dialog)
        self.description_label.setStyleSheet("selection-color: rgb(255, 119, 0);")
        self.description_label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.description_label.setWordWrap(True)
        self.description_label.setObjectName("description_label")
        self.verticalLayout_2.addWidget(self.description_label)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMinimumSize(QtCore.QSize(0, 110))
        self.label.setMaximumSize(QtCore.QSize(16777215, 110))
        self.label.setStyleSheet("selection-color: rgb(255, 119, 0);")
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.repo_btn = QtWidgets.QPushButton(Dialog)
        self.repo_btn.setStyleSheet("selection-background-color: rgb(255, 119, 0);")
        self.repo_btn.setObjectName("repo_btn")
        self.gridLayout.addWidget(self.repo_btn, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStyleSheet("selection-background-color: rgb(255, 119, 0);")
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "О клиенте Tinelix IRC"))
        self.progname.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Tinelix IRC Client </span><span style=\" font-size:8pt;\">(codename Flight)</span></p></body></html>"))
        self.description_label.setText(_translate("Dialog", "(description)"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p>Это свободное программное обеспечение с открытым исходным кодом, распространяемое в соответствии с условиями <a href=\"https://www.gnu.org/licenses/gnu-3.0.ru.html\"><span style=\" text-decoration: underline; color:#1d99f3;\">GNU General Public License 3.0 (прочитать лицензию)</span></a><span style=\" font-weight:600;\"/>.<br><br>БЕЗ КАКИХ-ЛИБО ГАРАНТИЙ, ВКЛЮЧАЯ КОММЕРЧЕСКУЮ ЦЕННОСТЬ.</body></html>"))
        self.label_2.setText(_translate("Dialog", "© 2021 Dmitry Tretyakov (aka. Tinelix)"))
        self.repo_btn.setText(_translate("Dialog", "Репозиторий"))
import resources_rc
