# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '005.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(351, 184)
        Dialog.setStyleSheet("background-color: rgb(43, 43, 43);\n"
"color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(Dialog)
        self.title_label.setMinimumSize(QtCore.QSize(0, 20))
        self.title_label.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.language_combo = QtWidgets.QComboBox(Dialog)
        self.language_combo.setMinimumSize(QtCore.QSize(160, 22))
        self.language_combo.setStyleSheet("border-color: rgb(255, 119, 0);\n"
"selection-background-color: rgb(161, 75, 0);")
        self.language_combo.setObjectName("language_combo")
        self.gridLayout.addWidget(self.language_combo, 0, 1, 1, 1)
        self.language_label = QtWidgets.QLabel(Dialog)
        self.language_label.setMinimumSize(QtCore.QSize(100, 30))
        self.language_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.language_label.setObjectName("language_label")
        self.gridLayout.addWidget(self.language_label, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.dark_theme_cb = QtWidgets.QCheckBox(Dialog)
        self.dark_theme_cb.setEnabled(True)
        self.dark_theme_cb.setMinimumSize(QtCore.QSize(110, 21))
        self.dark_theme_cb.setStyleSheet("border-color: rgb(255, 119, 0);\n"
"selection-background-color: rgb(255, 119, 0);")
        self.dark_theme_cb.setChecked(True)
        self.dark_theme_cb.setTristate(False)
        self.dark_theme_cb.setObjectName("dark_theme_cb")
        self.gridLayout_2.addWidget(self.dark_theme_cb, 0, 0, 1, 1)
        self.save_msghistory_cb = QtWidgets.QCheckBox(Dialog)
        self.save_msghistory_cb.setMinimumSize(QtCore.QSize(0, 21))
        self.save_msghistory_cb.setStyleSheet("border-color: rgb(255, 119, 0);\n"
"selection-background-color: rgb(255, 119, 0);")
        self.save_msghistory_cb.setObjectName("save_msghistory_cb")
        self.gridLayout_2.addWidget(self.save_msghistory_cb, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.msgs_hint = QtWidgets.QCheckBox(Dialog)
        self.msgs_hint.setEnabled(False)
        self.msgs_hint.setMinimumSize(QtCore.QSize(0, 21))
        self.msgs_hint.setStyleSheet("border-color: rgb(255, 119, 0);\n"
"selection-background-color: rgb(255, 119, 0);")
        self.msgs_hint.setObjectName("msgs_hint")
        self.verticalLayout_2.addWidget(self.msgs_hint)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setMinimumSize(QtCore.QSize(0, 33))
        self.buttonBox.setStyleSheet("selection-background-color: rgb(255, 119, 0);")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Настройки"))
        self.title_label.setText(_translate("Dialog", "Настройки"))
        self.language_label.setText(_translate("Dialog", "Язык (Language):"))
        self.dark_theme_cb.setText(_translate("Dialog", "Темная тема"))
        self.save_msghistory_cb.setText(_translate("Dialog", "Сохранять историю сообщений"))
        self.msgs_hint.setText(_translate("Dialog", "Подсказки при вводе текста"))
