# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'progresswindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(240, 140)
        Dialog.setMinimumSize(QtCore.QSize(240, 140))
        Dialog.setMaximumSize(QtCore.QSize(240, 140))
        Dialog.setWindowTitle("")
        Dialog.setStyleSheet("background-color: rgb(43, 43, 43);\n"
"color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.progresstext = QtWidgets.QLabel(Dialog)
        self.progresstext.setMinimumSize(QtCore.QSize(0, 24))
        self.progresstext.setMaximumSize(QtCore.QSize(16777215, 24))
        self.progresstext.setText("")
        self.progresstext.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.progresstext.setWordWrap(True)
        self.progresstext.setObjectName("progresstext")
        self.verticalLayout.addWidget(self.progresstext)
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 20))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 20))
        self.progressBar.setStyleSheet("selection-background-color: rgb(161, 75, 0);")
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setMinimumSize(QtCore.QSize(0, 24))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 24))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.propertie = QtWidgets.QLabel(self.frame)
        self.propertie.setMinimumSize(QtCore.QSize(80, 22))
        self.propertie.setMaximumSize(QtCore.QSize(80, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.propertie.setFont(font)
        self.propertie.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.propertie.setObjectName("propertie")
        self.gridLayout_2.addWidget(self.propertie, 0, 0, 1, 1)
        self.value = QtWidgets.QLabel(self.frame)
        self.value.setMinimumSize(QtCore.QSize(0, 22))
        self.value.setMaximumSize(QtCore.QSize(16777215, 22))
        self.value.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.value.setObjectName("value")
        self.gridLayout_2.addWidget(self.value, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout.addWidget(self.frame_2)
        self.additional_btn = QtWidgets.QPushButton(Dialog)
        self.additional_btn.setMinimumSize(QtCore.QSize(0, 24))
        self.additional_btn.setMaximumSize(QtCore.QSize(100, 24))
        self.additional_btn.setStyleSheet("selection-background-color: #ff7700;")
        self.additional_btn.setFlat(False)
        self.additional_btn.setObjectName("additional_btn")
        self.verticalLayout.addWidget(self.additional_btn)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.propertie.setText(_translate("Dialog", "Свойство:"))
        self.value.setText(_translate("Dialog", "Значение"))
        self.additional_btn.setText(_translate("Dialog", "Подробнее"))
import resources_rc
